Archomeda/Gw2Sharp

- CHANGELOG.md
- Gw2Sharp.Tests/WebApi/Gw2WebApiClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/BaseEndpointClientTests.cs
- Gw2Sharp/WebApi/Connection.cs
- Gw2Sharp/WebApi/Gw2WebApiClient.cs
- Gw2Sharp/WebApi/IGw2WebApiClient.cs
- Gw2Sharp/WebApi/IWebApiClientInternal.cs
- Gw2Sharp/WebApi/V2/Clients/BaseClient.cs
- Gw2Sharp/WebApi/V2/Clients/IClient.cs
- Gw2Sharp/WebApi/V2/Clients/IClientInternal.cs
- Gw2Sharp/WebApi/V2/Gw2WebApiV2Client.cs
- Gw2Sharp/WebApi/V2/IGw2WebApiV2Client.cs
It should only be used internally for the various endpoint clients. Consumers have nothing to gain from having it exposed.
> Make client interface internal

- CHANGELOG.md
- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
- Gw2Sharp.Tests/Json/Converters/ApiEnumConverterTests.cs
- Gw2Sharp.Tests/TestFiles/Guild/GuildId.3.json
- Gw2Sharp.Tests/WebApi/V2/Clients/BaseEndpointClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Guild/GuildIdClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Models/ApiEnumTests.cs
- Gw2Sharp.Tests/WebApi/V2/Models/ApiFlagsTests.cs
- Gw2Sharp/Extensions/EnumExtensions.cs
- Gw2Sharp/Json/Converters/ApiEnumConverter.cs
- Gw2Sharp/Json/Converters/ApiFlagsConverter.cs
- Gw2Sharp/WebApi/V2/Models/ApiEnum.cs
- Gw2Sharp/WebApi/V2/Models/ApiFlags.cs
- Gw2Sharp/WebApi/V2/Models/Guild/Guild.cs
The ApiEnum and ApiFlags classes are used to wrap possible unknown API enum values. In order to accomplish that, I created two variants of each class: the non-generic variant, and the generic variant. In practice, the user only uses the generic variant. The non-generic variant was there to support the custom JSON deserializer code. However, it causes issues like #10 when the default constructor was used. ApiFlags creates a list of ApiEnum objects, and because of the non-generic constructor, this was initialized as a list of ApiEnum objects, instead of a list of ApiEnum\<T\> objects. That causes an InvalidCastException when the list is accessed.
This change removes the non-generic variants of both classes, and changes the JSON deserializer to work with it. I also included tests for …
> Improve ApiEnum and ApiFlags

- .appveyor.yml
- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .gitlab-ci.yml
This updates CI related files from .NET Core 3.0 Preview 7 to the release version of .NET Core 3.0.
Preview 8 and 9 were skipped due to bugs as mentioned in #13. And it seems that the release version is stable again.
Resolves #13
> Update to .NET Core 3.0 release version

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .gitlab-ci.yml
Use .NET Core 3.1 for building the projects, because .NET Core 3.0 will be deprecated in the upcoming months.
> Use .NET Core 3.1

- Gw2Sharp.Tests/TestFiles/Characters/Characters.bulk.json
- Gw2Sharp/Json/Converters/GuidConverter.cs
- Gw2Sharp/WebApi/V2/Models/Characters/Character.cs
Checks if reader TokenType is null.  If it is, it returns `Guid.Empty`, otherwise it returns the Guid.
Fixes #27.
> Add null check to GuidConverter.

- Gw2Sharp.Tests/WebApi/Caching/BaseCacheMethodTests.cs
- Gw2Sharp.Tests/WebApi/Caching/NullCacheMethodTests.cs
- Gw2Sharp/WebApi/Caching/ArchiveCacheMethod.cs
- Gw2Sharp/WebApi/Caching/BaseCacheMethod.cs
- Gw2Sharp/WebApi/Caching/ICacheMethod.cs
- Gw2Sharp/WebApi/Caching/MemoryCacheMethod.cs
- Gw2Sharp/WebApi/Caching/NullCacheMethod.cs
Starting with v0.8.0 this method will be named differently to avoid confusion.
The old method is deprecated first, and in v0.9.0 and higher it will be removed.
> Deprecate ICacheMethod.FlushAsync in favor of ClearAsync

- Gw2Sharp/Mumble/Gw2LinkedMem.cs
Gw2Sharp was using the wrong size when opening the Mumble Link memory mapped file, causing all kinds of weird stuff.
> Fix wrong Mumble Link struct size

- Gw2Sharp.Tests/WebApi/V2/Models/ApiEnumTests.cs
- Gw2Sharp/WebApi/V2/Models/ApiEnum.cs
For example, the TokenPermissions enum is PascalCase in Gw2Sharp, while the API lists the permissions in camelCase (or just lowercase). When checking if an enum is present in these flags, it will fail if the casing is incorrect.
The solution is to compare them case insensitively, since we're deserializing the enums case insensitively anyway.
> Compare ApiEnum's raw values case insensitively

- CHANGELOG.md
- GitVersion.yml
- Gw2Sharp.Tests/ChatLinks/BuildChatLinkTests.cs
- Gw2Sharp.Tests/Mumble/Gw2MumbleClientTests.cs
- Gw2Sharp/ChatLinks/BuildChatLink.cs
- Gw2Sharp/ChatLinks/Structs/BuildChatLinkStruct.cs
- Gw2Sharp/Gw2Sharp.csproj
- Gw2Sharp/Models/LegendType.cs
- Gw2Sharp/Models/ProfessionType.cs
- Gw2Sharp/Models/RaceType.cs
- Gw2Sharp/Mumble/Gw2MumbleClient.cs
- Gw2Sharp/Mumble/IGw2MumbleClient.cs
- Gw2Sharp/Mumble/Models/CharacterIdentity.cs
- Gw2Sharp/WebApi/V2/Clients/IBulkAliasExpandableClient.cs
- Gw2Sharp/WebApi/V2/Clients/Legends/ILegendsClient.cs
- Gw2Sharp/WebApi/V2/Clients/Legends/LegendsClient.cs
- Gw2Sharp/WebApi/V2/Clients/Professions/IProfessionsClient.cs
- Gw2Sharp/WebApi/V2/Clients/Professions/ProfessionsClient.cs
- Gw2Sharp/WebApi/V2/Clients/Races/IRacesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Races/RacesClient.cs
- MumbleLinkReader/Form1.cs
Closes #40.
After looking through the code, there was no reason why it was done this way. The original intention was to emulate the expected id type in the web API, which is a string (as was done with the race). However, the profession was using an enum type. This introduced inconsistency.
This PR resolves this inconsistency. For easiness, the Mumble Client returns enums now. And the respective endpoints that accept either a legend, profession or race as id, will also accept these enum counterparts.
This is a breaking change, and will be introduced in v0.9.0.
> Combine shared enums usage

- CHANGELOG.md
- Gw2Sharp/Mumble/Gw2MumbleClient.cs
Closes #39.
Added a boolean that indicates whether the Mumble identity has already been compared to the previous one.
Without this boolean, requesting an identity field will always compare the JSON strings to see if the identity has been updated since last time. This causes an overhead when we can just set a boolean that will be reset when it's actually updated and we need to check the strings again.
> Skip unnecessarily comparing strings for Mumble identity

- CHANGELOG.md
- Gw2Sharp/Mumble/Gw2LinkedMem.cs
- Gw2Sharp/Mumble/Gw2MumbleClient.cs
Requesting the server address doesn't allocate any more memory when it's not needed.
This also adds a lock around the identity and the server address, since they both have a caching backing field and we don't want any race conditions happening here that may cause undefined behavior.
> Cache Mumble Link server address as well

- Gw2Sharp.Tests/TestFiles/Pvp/PvpGames.bulk.json
- Gw2Sharp.Tests/WebApi/V2/Clients/BaseEndpointClientTests.cs
- Gw2Sharp/WebApi/V2/Models/Characters/ItemEquipmentLocationType.cs
- Gw2Sharp/WebApi/V2/Models/Pvp/PvpRatingType.cs
This new enum value was added some time ago.
It's named as `TwoVTwoRanked` in the enum, because of C# limitations.
I also fixed the tests where it checks if the given enum values of a JSON test file, all exist in the respective enum definition. Deserializing went okay, because it already checked the `EnumMemberAttribute`, however the test did not.
Need to follow up on #52 for a possible performance bottleneck I noticed.
> Add 2v2Ranked in PvpRatingType

- CHANGELOG.md
- Gw2Sharp.Tests/WebApi/Caching/BaseCacheMethodTests.cs
- Gw2Sharp/WebApi/Caching/BaseCacheMethod.cs
> Fix getting many items from cache when an item does not exist

- Gw2Sharp/Models/LegendType.cs
ArenaNet changed the legend enum again. This time to start from 1.
Hopefully this is the last time.
> Update legend enum once and for all

- Gw2Sharp.Tests/WebApi/Caching/ArchiveCacheMethodTests.cs
- Gw2Sharp.Tests/WebApi/Caching/BaseCacheMethodTests.cs
- Gw2Sharp/WebApi/Caching/ArchiveCacheMethod.cs
Caching with an archive as backing storage has apparently been broken for a while.
This will fix it with a temporary solution until v0.12.
Because the new middleware now handles raw JSON strings, it's possible to introduce a breaking change to `ICacheMethod` to only accept a raw byte array and raw (JSON) string instead of a generic type. This will make it easier for archive caching since no JSON (de)serializing needs to be done. This is planned for v0.12 (#71).
> Fix archive caching

- .github/workflows/ci.yml
- .github/workflows/publish-version.yml
Support for set-env support has been removed last week, causing CI failures.
This will change to GitVersion's action instead of using our own PowerShell script to version the built assemblies, which also doesn't use set-env anymore.
https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
> Swap GitVersion to action to fix set-env support

- .github/workflows/sonarcloud.yml
Forked repositories don't have access to the SonarCloud secret, therefore always failing the check.
This will (hopefully) skip the check.
> Skip SonarCloud in PRs from forked repos

- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
- Gw2Sharp/Gw2Sharp.csproj
FxCopAnalyzers is now deprecated: https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019
> Use .NET analyzers, replacing FxCopAnalyzers

- CHANGELOG.md
- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
- Gw2Sharp.Tests/TestFiles/Characters/Characters.EquipmentTabs.Null.json
- Gw2Sharp.Tests/TestFiles/Characters/Characters.EquipmentTabs.json
- Gw2Sharp.Tests/TestFiles/Characters/Characters.single.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.bulk.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.single.json
- Gw2Sharp.Tests/WebApi/V2/Clients/BaseEndpointClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Characters/CharactersClientTests.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersClient.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersIdEquipmentTabsActiveClient.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersIdEquipmentTabsClient.cs
- Gw2Sharp/WebApi/V2/Models/Characters/Character.cs
- Gw2Sharp/WebApi/V2/Models/Characters/CharacterEquipmentTabSlot.cs
- docs/guides/endpoints.md
The `2021-04-06T21:00:00.000Z` schema has moved the PvP equipment under the `equipment_tabs` property.
This PR reflects that change, with automatic rollforward from the now deprecated `equipment_pvp` under the root character object.
> Update to the latest character schema for equipment_pvp changes

- docs/guides/exception-handling.md
The exception page in the docs has invalid links to the exception classes. They were moved some time ago, but I forgot to update these references.
> Fix documentation exception links

- Gw2Sharp.Tests/ConnectionTests.cs
- Gw2Sharp/Connection.cs
The Gw2Sharp version that's reported in the UserAgent was always x.0.0.0 due to how our assembly versioning works. It will now (try to) grab the FileVersion instead of the AssemblyVersion that has a more accurate version.
> Fix UserAgent version reporting

- Gw2Sharp.Tests/WebApi/Middleware/ExceptionMiddlewareTests.cs
- Gw2Sharp/WebApi/Middleware/ExceptionMiddleware.cs
Failing API responses that don't have a JSON body currently throw the `UnexpectedStatusException` which is incorrect if the server responded with e.g. a 500 code. This fixes the exception type to be its proper exception type.
> Fix exception type when the result is not JSON

- .github/workflows/ci.yml
- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
- Gw2Sharp.Tests/Mumble/Gw2MumbleClientTests.cs
- Gw2Sharp/ChatLinks/Gw2ChatLink.cs
- Gw2Sharp/Connection.cs
- Gw2Sharp/Gw2Client.cs
- Gw2Sharp/Gw2Sharp.csproj
- Gw2Sharp/IGw2Client.cs
- Gw2Sharp/Mumble/Gw2MumbleClient.cs
- Gw2Sharp/WebApi/Http/WebApiRequest.cs
- docs/guides/introduction.md
This adds a separate .NET 5 target in order to make use of the new attributes that can check for platform support. We'll use this for the Mumble Link API, which is only available on Windows. Using this API on any other platform will raise a compiler warning.
We now also explicitly throw the `PlatformNotSupportedException` on non-Windows versions ourselves, instead of letting it being handled by the underlying .NET system.
> Add .NET 5 target

- Gw2Sharp.Tests/Json/Converters/ApiEnumConverterTests.cs
- Gw2Sharp.Tests/Json/Converters/ApiFlagsConverterTests.cs
- Gw2Sharp.Tests/TestFiles/Characters/Characters.single.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipment.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.bulk.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.single.json
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersClient.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersIdClient.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersIdEquipmentTabsActiveClient.cs
- Gw2Sharp/WebApi/V2/Clients/Characters/CharactersIdEquipmentTabsClient.cs
- Gw2Sharp/WebApi/V2/Models/Characters/ItemEquipmentLocationType.cs
This updates the main character endpoint, and the equipment tab subendpoint to schema `2021-07-15T13:00:00.000Z` that includes the `EquippedFromLegendaryArmory` and `LegendaryArmory` enum values for the equipment location.
Coincidentally, this also fixes the oversight where the individual character by id endpoint didn't have the latest schema version applied, resulting in `Client.Characters["character-name"].GetAsync()` using the old schema `2019-12-19T00:00:00.000Z` that didn't have the changes of `equipment_pvp` applied from schema `2021-04-06T21:00:00.000Z`.
> Add new legendary armory location enum values

- Gw2Sharp/WebApi/Caching/CacheItemStatus.cs
- Gw2Sharp/WebApi/Caching/CacheItemType.cs
- Gw2Sharp/WebApi/V2/Models/Characters/ItemEquipmentLocationType.cs
- Gw2Sharp/WebApi/V2/Models/Professions/ProfessionFlag.cs
- Gw2Sharp/WebApi/V2/Models/Professions/ProfessionTrainingCategory.cs
- Gw2Sharp/WebApi/V2/Models/Professions/ProfessionTrainingTrackStepType.cs
- Gw2Sharp/WebApi/V2/Models/Professions/ProfessionWeaponFlag.cs
- Gw2Sharp/WebApi/V2/Models/Pvp/PvpSeasonDivisionFlag.cs
- Gw2Sharp/WebApi/V2/Models/Pvp/PvpSeasonLeaderboardScoringOrder.cs
- Gw2Sharp/WebApi/V2/Models/Pvp/PvpSeasonLeaderboardScoringType.cs
- Gw2Sharp/WebApi/V2/Models/Pvp/PvpSeasonLeaderboardSettingsTierType.cs
- Gw2Sharp/WebApi/V2/Models/Raids/RaidWingEventType.cs
- Gw2Sharp/WebApi/V2/Models/SkillType.cs
- Gw2Sharp/WebApi/V2/Models/Skills/ComboFieldType.cs
- Gw2Sharp/WebApi/V2/Models/Skills/ComboFinisherType.cs
- Gw2Sharp/WebApi/V2/Models/Skills/SkillFlag.cs
- Gw2Sharp/WebApi/V2/Models/Skins/SkinFlag.cs
- Gw2Sharp/WebApi/V2/Models/Stories/StoryFlag.cs
Some enums somehow got the wrong namespace. They were placed in the root Gw2Sharp namespace, instead of `Gw2Sharp.WebApi.V2.Models` or `Gw2Sharp.WebApi.V2.Caching`.
> Fix namespaces of various enums

- Gw2Sharp.Tests/WebApi/V2/Clients/Characters/CharactersClientTests.cs
- Gw2Sharp/WebApi/V2/Models/Characters/Character.cs
This will make the deprecated equipment PvP part of the characters endpoint uncompilable with a hint of what the replacement is. If the property is somehow still accessed (e.g. via reflection), it will throw a NotSupportedException because the code to support the backwards compatibility has been removed entirely.
> Make deprecated equipment PvP property uncompilable

- .github/workflows/command-cleanup.yml
- .github/workflows/command-test.yml
Updating the /test command to include .NET 5, and hopefully fixing the /cleanup command so that it builds before cleaning up, and therefore no longer deleting every using statement that's actually still referenced.
> Update commands and hopefully fix the cleanup

- Gw2Sharp.Tests/WebApi/V2/Clients/Wvw/BaseWvwMatchesWorldClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Wvw/WvwMatchesOverviewWorldClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Wvw/WvwMatchesScoresWorldClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Wvw/WvwMatchesStatsWorldClientTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/Wvw/WvwMatchesWorldClientTests.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwAbilitiesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesOverviewClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesOverviewWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesScoresClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesScoresWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesStatsClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesStatsWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwMatchesWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwObjectivesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwRanksClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/IWvwUpgradesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesOverviewClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesOverviewWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesScoresWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesStatsWorldClient.cs
- Gw2Sharp/WebApi/V2/Clients/Wvw/WvwMatchesWorldClient.cs
This adds support for the `world` parameter for various WvW matches endpoints.
Closes #95
> Add world parameter support for WvW matches endpoints

- Gw2Sharp.Tests/WebApi/Exceptions/RequestExceptionTests.cs
- Gw2Sharp.Tests/WebApi/Exceptions/UnexpectedStatusExceptionTests.cs
- Gw2Sharp.Tests/WebApi/Middleware/ExceptionMiddlewareTests.cs
- Gw2Sharp/WebApi/Exceptions/AuthorizationRequiredException.cs
- Gw2Sharp/WebApi/Exceptions/BadRequestException.cs
- Gw2Sharp/WebApi/Exceptions/InvalidAccessTokenException.cs
- Gw2Sharp/WebApi/Exceptions/MembershipRequiredException.cs
- Gw2Sharp/WebApi/Exceptions/MissingScopesException.cs
- Gw2Sharp/WebApi/Exceptions/NotFoundException.cs
- Gw2Sharp/WebApi/Exceptions/RequestException.cs
- Gw2Sharp/WebApi/Exceptions/RestrictedToGuildLeadersException.cs
- Gw2Sharp/WebApi/Exceptions/ServerErrorException.cs
- Gw2Sharp/WebApi/Exceptions/ServiceUnavailableException.cs
- Gw2Sharp/WebApi/Exceptions/TooManyRequestsException.cs
- Gw2Sharp/WebApi/Exceptions/UnexpectedStatusException.cs
- Gw2Sharp/WebApi/Http/IWebApiResponse.cs
- Gw2Sharp/WebApi/Http/WebApiResponse.cs
- Gw2Sharp/WebApi/Middleware/ExceptionMiddleware.cs
The generic typed exceptions have been entirely removed, making it easier to catch exceptions thrown from Gw2Sharp.
This is a breaking change, and is going to be effective starting from version 2.0.
Closes #96
> Refactor web API exceptions

- CHANGELOG.md
- Gw2Sharp.Tests/Json/Converters/RenderUrlConverterTests.cs
- Gw2Sharp.Tests/WebApi/Gw2WebApiClientTests.cs
- Gw2Sharp.Tests/WebApi/RenderUrlTests.cs
- Gw2Sharp.Tests/WebApi/V2/Clients/BaseEndpointClientTests.cs
- Gw2Sharp/Connection.cs
- Gw2Sharp/IConnection.cs
- Gw2Sharp/Json/Converters/RenderUrlConverter.cs
- Gw2Sharp/WebApi/Gw2WebApiClient.cs
- Gw2Sharp/WebApi/Http/WebApiRequest.cs
- Gw2Sharp/WebApi/RenderUrl.cs
- Gw2Sharp/WebApi/V2/Clients/BaseEndpointClient.cs
- Gw2Sharp/WebApi/V2/Gw2WebApiV2Client.cs
- docs/guides/proxy.md
- docs/guides/toc.yml
This will make the API hostnames configurable through the Connection class. Both the API hostname and the render hostname can be swapped to a custom base URL one.
Closes #108
> Implement configurable API and render base URLs

- CHANGELOG.md
- Gw2Sharp.Tests/ConnectionTests.cs
- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
- Gw2Sharp.Tests/Mumble/Gw2MumbleClientReaderTests.cs
- Gw2Sharp.Tests/Mumble/Gw2MumbleClientTests.cs
- Gw2Sharp/Connection.cs
- Gw2Sharp/Gw2Client.cs
- Gw2Sharp/IConnection.cs
- Gw2Sharp/IGw2Client.cs
- Gw2Sharp/Mumble/Gw2LinkedMem.cs
- Gw2Sharp/Mumble/Gw2MumbleClient.cs
- Gw2Sharp/Mumble/Gw2MumbleClientReader.cs
- Gw2Sharp/Mumble/IGw2MumbleClient.cs
- Gw2Sharp/Mumble/IGw2MumbleClientReader.cs
- Gw2Sharp/Mumble/Models/UiState.cs
- Gw2Sharp/Mumble/UnsupportedMumblePlatformClientReader.cs
This adds support for providing a custom Mumble Link reader. By default this is set to what it always was on Windows. For any other operating system, this is set to a reader that just returns `NotSupportedException`. The functionality effectively stays the same as before.
`SupportedOSPlatformAttribute` has been removed in certain areas because it can't be included anymore with this construction, instead it's now placed explicitly on the default `Gw2MumbleClientReader` that's used on Windows.
A bunch of structs have been publicized because they are necessary for the Mumble Link reader interface.
> Custom Mumble Link reader

- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.bulk.json
- Gw2Sharp.Tests/TestFiles/Characters/CharactersIdEquipmentTabs.single.json
- Gw2Sharp/WebApi/V2/Models/Characters/CharacterEquipmentTabSlot.cs
The names for the equipment tab slots were missing.
> Add missing equipment tab slot name

- .github/workflows/ci.yml
- .github/workflows/command-test.yml
- .github/workflows/publish-version.yml
- .github/workflows/release.yml
- .github/workflows/sonarcloud.yml
- .github/workflows/update-docs.yml
- Gw2Sharp.Tests/Gw2Sharp.Tests.csproj
.NET Core 2.1 hasn't been supported for some time now, but we were still testing against it. This is now removed. I've replaced it with .NET 6.
Gw2Sharp itself doesn't target .NET 6 yet.
Will start merging this once GitHub actions include .NET 6 by default for ubuntu agents...
> Remove netcoreapp2.1 and add net6.0 for testing

- Gw2Sharp/WebApi/V2/Models/Skills/Skill.cs
Some skills appear to have no icon returned by the API.
For example: https://api.guildwars2.com/v2/skills?ids=52116
```json
[
{
"name": "Largos' Domain",
"facts": [
{
"text": "Recharge",
"type": "Recharge",
"icon": "https://render.guildwars2.com/file/D767B963D120F077C3B163A05DC05A7317D7DB70/156651.png",
"value": 2
},
{
"text": "Apply Buff/Condition",
"type": "Buff",
"icon": "https://render.guildwars2.com/file/FB5C627D1A6A46807AF77165604A27FE804B056F/2039793.png",
"duration": 20,
"status": "Waterlogged",
"description": "As you become more waterlogged, you become more susceptible to the largos' water magic. If you become fully waterlogged at maximum stacks, you will be assassinated.",
"apply_count": 1
}
],
"description": "",
"flags": [],
"id": 52116,
"chat_link": "[&BpTLAAA=]"
}
]
```
When …
> Make Skill Icon nullable.

- Gw2Sharp.Tests/WebApi/Middleware/CacheMiddlewareTests.cs
- Gw2Sharp/WebApi/Middleware/CacheMiddleware.cs
> Fix many item caching so that individual items have proper cache ids

- Gw2Sharp/WebApi/V2/Clients/Raids/RaidsClient.cs
There's a typo in the attribute, causing a 404 upon requesting.
Fixes #122
> Fix /v2/raids endpoint 404

- Gw2Sharp/WebApi/V2/Clients/Account/IAccountClient.cs
fixes this tooltip:
because without unlocks scope this exception was thrown:
> IAccountProgressionClient:  add "unlocks" scope to tooltip

- Gw2Sharp.Tests/Json/Converters/CastableTypeConverterTests.cs
- Gw2Sharp/Json/Converters/CastableTypeConverter.cs
Fixes #120 
Allowing strict type checking on request seemed to much of an effort to support for now. So instead it now never throws an exception in the case when a castable type is not defined for a new enum value.
> Deserialize to the base type if the castable type is not defined in code
